"use client";

import { apiFetch } from "./api";

/** Converts the VAPID public key (base64url, as generated by web-push) into
 * the Uint8Array PushManager.subscribe expects. */
function urlBase64ToUint8Array(base64: string): Uint8Array {
  const padding = "=".repeat((4 - (base64.length % 4)) % 4);
  const base64Safe = (base64 + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(base64Safe);
  const outputArray = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; ++i) {
    outputArray[i] = raw.charCodeAt(i);
  }
  return outputArray;
}

export function pushSupported(): boolean {
  return typeof window !== "undefined" && "serviceWorker" in navigator && "PushManager" in window;
}

export async function getPushSubscription(): Promise<PushSubscription | null> {
  if (!pushSupported()) return null;
  const registration = await navigator.serviceWorker.getRegistration();
  return (await registration?.pushManager.getSubscription()) ?? null;
}

/** Registers the service worker (idempotent — safe to call on every load),
 * asks for Notification permission, subscribes, and saves the subscription
 * on the backend. Throws if the user denies permission or the browser lacks
 * support — callers should surface that as "couldn't enable notifications." */
export async function enablePush(): Promise<void> {
  if (!pushSupported()) throw new Error("Push notifications aren't supported in this browser.");

  const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
  if (!publicKey) throw new Error("Push notifications aren't configured.");

  const permission = await Notification.requestPermission();
  if (permission !== "granted") throw new Error("Notification permission was denied.");

  await navigator.serviceWorker.register("/sw.js");
  const registration = await navigator.serviceWorker.ready;

  // Unsubscribe any stale existing subscription to avoid VAPID key mismatch errors
  let subscription = await registration.pushManager.getSubscription();
  if (subscription) {
    try {
      await subscription.unsubscribe();
    } catch {
      // Ignore failure to unsubscribe stale subscription
    }
  }

  try {
    subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(publicKey) as unknown as BufferSource,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes("push service error") || msg.includes("Registration failed")) {
      throw new Error(
        "Browser push service error. If using Brave, turn on 'Google Services for Push Messaging' in Settings → Privacy. Otherwise check your internet connection."
      );
    }
    throw err;
  }

  const json = subscription.toJSON();
  await apiFetch("/notifications/push-subscription", {
    method: "POST",
    body: JSON.stringify({ endpoint: json.endpoint, keys: json.keys }),
  });
}

export async function disablePush(): Promise<void> {
  const subscription = await getPushSubscription();
  if (!subscription) return;

  await apiFetch("/notifications/push-unsubscribe", {
    method: "POST",
    body: JSON.stringify({ endpoint: subscription.endpoint }),
  }).catch(() => {});
  await subscription.unsubscribe();
}
